CREATE DATABASE IF NOT EXISTS db1;

use db1;

DROP TABLE IF EXISTS EMP2;
DROP TABLE IF EXISTS DEPT2;



CREATE TABLE DEPT2 (
                       DEPTNO	INT AUTO_INCREMENT NOT NULL,
                       DNAME	  VARCHAR(14),
                       LOC		  VARCHAR(13),
                       CONSTRAINT DEPT2_PRIMARY_KEY PRIMARY KEY (DEPTNO)
);

INSERT INTO DEPT2 (DNAME,LOC) VALUES ('財務部','臺灣台北');
INSERT INTO DEPT2 (DNAME,LOC) VALUES ('研發部','臺灣新竹');
INSERT INTO DEPT2 (DNAME,LOC) VALUES ('業務部','美國紐約');
INSERT INTO DEPT2 (DNAME,LOC) VALUES ('生管部','中國上海');



CREATE TABLE EMP2 (
                      EMPNO     INT AUTO_INCREMENT NOT NULL,
                      ENAME     VARCHAR(10),
                      JOB       VARCHAR(9),
                      HIREDATE  DATE,
                      SAL       DECIMAL(7,2),
                      COMM      DECIMAL(7,2),
                      DEPTNO    INT NOT NULL,
                      CONSTRAINT EMP2_DEPTNO_FK FOREIGN KEY (DEPTNO) REFERENCES DEPT2 (DEPTNO),
                      CONSTRAINT EMP2_EMPNO_PK PRIMARY KEY (EMPNO)
) ;

INSERT INTO EMP2 (ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)  VALUES ('KING'  ,'PRESIDENT',STR_TO_DATE('1981-11-17','%Y-%m-%d'),5000.5,0.0 ,1);
INSERT INTO EMP2 (ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)  VALUES ('BLAKE' ,'MANAGER'  ,STR_TO_DATE('1981-05-01','%Y-%m-%d'),2850.0,0.0 ,3);
INSERT INTO EMP2 (ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)  VALUES ('CLARK' ,'MANAGER'  ,STR_TO_DATE('1981-01-09','%Y-%m-%d'),2450.0,0.0 ,1);
INSERT INTO EMP2 (ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)  VALUES ('JONES' ,'MANAGER'  ,STR_TO_DATE('1981-04-02','%Y-%m-%d'),2975.0,0.0 ,2);
INSERT INTO EMP2 (ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)  VALUES ('MARTIN','SALESMAN' ,STR_TO_DATE('1981-09-28','%Y-%m-%d'),1250.0,1400,3);
INSERT INTO EMP2 (ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)  VALUES ('ALLEN' ,'SALESMAN' ,STR_TO_DATE('1981-02-02','%Y-%m-%d'),1600.0,300 ,3);
INSERT INTO EMP2 (ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)  VALUES ('TURNER','SALESMAN' ,STR_TO_DATE('1981-09-28','%Y-%m-%d'),1500.0,0.0 ,3);
INSERT INTO EMP2 (ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)  VALUES ('JAMES' ,'CLERK'    ,STR_TO_DATE('1981-12-03','%Y-%m-%d'), 950.0,0.0 ,3);
INSERT INTO EMP2 (ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)  VALUES ('WARD'  ,'SALESMAN' ,STR_TO_DATE('1981-02-22','%Y-%m-%d'),1250.0,500 ,3);
INSERT INTO EMP2 (ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)  VALUES ('FORD'  ,'ANALYST'  ,STR_TO_DATE('1981-12-03','%Y-%m-%d'),3000.0,0.0 ,2);
INSERT INTO EMP2 (ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)  VALUES ('SMITH' ,'CLERK'    ,STR_TO_DATE('1980-12-17','%Y-%m-%d'), 800.0,0.0 ,2);
INSERT INTO EMP2 (ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)  VALUES ('SCOTT' ,'ANALYST'  ,STR_TO_DATE('1981-12-09','%Y-%m-%d'),3000.0,0.0 ,2);
INSERT INTO EMP2 (ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)  VALUES ('ADAMS' ,'CLERK'    ,STR_TO_DATE('1983-01-12','%Y-%m-%d'),1100.0,0.0 ,2);
INSERT INTO EMP2 (ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)  VALUES ('MILLER','CLERK'    ,STR_TO_DATE('1982-01-23','%Y-%m-%d'),1300.0,0.0 ,1);

